const mongoose=require('mongoose')

const add_contact=new mongoose.Schema({
title:{type:String},
first_name:{type:String},
last_name:{type:String},
country_code:{type:String},
mobile_no:{type:String},
mobile_type:{type:String},
email:{type:String},
email_type:{type:String},
title_company:{type:String},
designation:{type:String},
company_name:{type:String},
tags:{type:String},
father_husband_name:{type:String},
h_no:{type:String},
street_address:{type:String},
location:{type:String},
city:{type:String},
pincode:{type:String},
state:{type:String},
country:{type:String},
source:{type:String},
category:{type:String},
owner:{type:String},
team:{type:String},
gender:{type:String},
visible_to:{type:String},
maritial_status:{type:String},
birth_date:{type:String},
anniversary_date:{type:String},
education:{type:Array},
degree:{type:Array},
school_college:{type:Array},
loan:{type:String},
bank:{type:String},
amount:{type:String},
social_media:{type:String},
url:{type:String},
income:{type:String},
amount1:{type:String},
website:{type:String},
industry:{type:String},
descriptions:{type:String},

},{timestamps:true})

const addcontact=mongoose.model('add_contact',add_contact)
module.exports=addcontact